### ISSUE TITLE
Account request failed: Unlinked device

### ISSUE THREAD

**Issue by elsorino** [2secslater/DiscordAndU#3]
Been trying to make this work, but I keep getting an unlinked device error. My device ID has a letter in it(C) which requires me to add quotes to the DEVICE_ID or else it's a syntax error, maybe this is apart of the problem?

```
python .\dau.py
RPC connection successful.
HTTP request returned status code 400
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<errors>
    <error>
        <code>0110</code>
        <message>Unlinked device</message>
    </error>
</errors>

Traceback (most recent call last):
  File ".\dau.py", line 122, in <module>
    api.login(USERNAME, PASSWORD)
  File "C:\Users\elso\Documents\new.au\nintendo\account.py", line 207, in login
    response = request.get(
  File "C:\Users\elso\Documents\new.au\nintendo\account.py", line 146, in get
    return self.request(req)
  File "C:\Users\elso\Documents\new.au\nintendo\account.py", line 159, in request
    raise AccountRequestError("Account request failed: %s" %content.error.message.text)
nintendo.account.AccountRequestError: Account request failed: Unlinked device
```

Config file:
```

# Wii U Console Details
DEVICE_ID = "NumbersC96"
SERIAL_NUMBER = "Correct"
# 5.5.1 = 0x220, 5.5.2 = 0x230
SYSTEM_VERSION = 0x240 
# USA = 2, EUR = 4
REGION = 2
COUNTRY = "US"

# Wii U Secondary User/Account Details
USERNAME = "correct"
PASSWORD = "correct"

# Wii U Main User/Account NNID
MAINID = "elsorino"


```

**Comment by CalmCreative** [comment]
Hi elsorino,

I cloned this project a couple of days ago and had the same problem.
Thankfully, the solution to fix this issue is quite straightforward.

On the 'DEVICE_ID' line, instead of using quotes, treat it like a hex value.

eg, instead of **"12345678"** change it to **0x12345678**.
